apiVersion: v1
kind: ConfigMap
metadata:
  name: app-service-config
data:
  flask_env: "production" # Replace with Helm: {{ .Values.env.FLASK_ENV }}
  host: "0.0.0.0" # Replace with Helm: {{ .Values.appService.hostIP }}
  name: "app-service" # Replace with Helm: {{ .Values.appService.host }}
  port: "5000" # Replace with Helm: {{ .Values.appService.port }}
  model_service_url: "http://model-service" # Replace with Helm: "http://{{ .Values.modelService.host }}"
