apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-deployment
  labels:
    app: app-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla25-team15/app-service
          ports:
            - containerPort: 5000 # Replace with Helm: {{ .Values.appService.port }}
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-service-config
                  key: flask_env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-service-config
                  key: name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-service-config
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: app-service-config
                  key: host
            - name: MODEL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-service-config
                  key: model_service_url
