apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  selector:
    app: app-service
  ports:
    - protocol: TCP
      port: 80 # Replace with Helm: {{ .Values.appService.port }}
      targetPort: 5000 # Replace with Helm: {{ .Values.appService.port }}
  type: ClusterIP
