apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-myprom-alertmanager
  namespace: monitoring
  labels:
    alertmanager: myprom-alertmanager
    app: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: slack-notifications
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1m
      routes:
        - match:
            severity: warning
          receiver: slack-notifications

    receivers:
      - name: slack-notifications
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#new-channel'  # Replace with helm
            text: "{{ range .Alerts }}*{{ .Annotations.summary }}*\n{{ .Annotations.description }}\n{{ end }}"
            send_resolved: true