apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: frontend-request-alerts
  namespace: monitoring
  labels:
    release: myprom
spec:
  groups:
    - name: frontend.rules
      rules:
        - alert: HighFrontendRequestRate
          expr: rate(frontend_prediction_requests_total[10s]) > 1
          labels:
            severity: warning
          annotations:
            summary: High number of frontend prediction requests
            description: "The frontend_prediction_requests_total counter has exceeded 300."
