apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-service-config
data:
  flask_env: {{ .Values.env.FLASK_ENV | quote }}
  name: {{ .Values.modelService.host | quote }}
  port: {{ .Values.modelService.port | quote }}
  host: {{ .Values.modelService.hostIP | quote }}
  model_version.v1: {{ .Values.modelService.versions.v1.modelVersion | quote }}
  model_version.v2: {{ .Values.modelService.versions.v2.modelVersion | quote }}
  model_file_name: {{ .Values.modelService.modelFileName | quote }}
  cv_file_name: {{ .Values.modelService.cvFileName | quote }}
