apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-model-service-secrets
type: Opaque
data:
  MODEL_RESOURCE_URI: {{ .Values.modelService.secrets.MODEL_RESOURCE_URI }}
  CV_URI: {{ .Values.modelService.secrets.CV_URI }}