services:
  app-service:
    image: ghcr.io/remla25-team15/app-service
    container_name: app-service
    expose:
      - ${APP_SERVICE_PORT}
    environment:
      - FLASK_ENV=production
      - APP_NAME=app-service
      - PORT=${APP_SERVICE_PORT}
      - HOST=0.0.0.0
      - MODEL_SERVICE_URL=http://${MODEL_SERVICE_HOST}:${MODEL_SERVICE_PORT}
    volumes:
      - ./secrets/dummy_secret.txt:/run/secrets/dummy_secret:ro
    restart: unless-stopped

  app-frontend:
    image: ghcr.io/remla25-team15/app-frontend
    container_name: app-frontend
    expose:
      - ${FRONTEND_PORT}
    environment:
      - FLASK_ENV=production
      - APP_SERVICE_URL=http://${APP_SERVICE_HOST}:${APP_SERVICE_PORT}
      - PORT=${FRONTEND_PORT}
    restart: unless-stopped

  model-service:
    image: ghcr.io/remla25-team15/model-service
    container_name: model-service
    expose:
      - ${MODEL_SERVICE_PORT}
    environment:
      - FLASK_ENV=production
      - RESOURCE_BASE_URL=${RESOURCE_BASE_URL}
      - MODEL_FILE_NAME=${MODEL_FILE_NAME}
      - CV_FILE_NAME=${CV_FILE_NAME}
      - PORT=${MODEL_SERVICE_PORT}
      - MODEL_VERSION=${MODEL_VERSION}
    volumes:
      - model-cache:/models
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fallback.html:/usr/share/nginx/html/fallback.html
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app-service
      - model-service
      - app-frontend
    restart: unless-stopped

volumes:
  model-cache:

networks:
  default:
    name: remla-network
