services:
  app-service:
    build:
      context: ../app-service
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    volumes:
      - ../app-service:/app
    expose:
      - "5000:5000"

  app-frontend:
    build:
      context: ../app-frontend
    environment:
      - FLASK_ENV=development
      - APP_SERVICE_URL=http://app-service:5000
      - DEBUG=True
    volumes:
      - ../app-frontend:/app
    ports:
      - "3000:3000"

  model-service:
    build:
      context: ../model-service
    environment:
      - FLASK_ENV=development
      - PORT=5001
      - DEBUG=True
    volumes:
      - ../model-service:/app
      - model-cache:/models
    ports:
      - "5001:5001"

volumes:
  model-cache:
