apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: {{ .Values.alertmanager.namespace }}
  labels:
    app: alertmanager
    release: {{ .Release.Name }}
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: '{{ .Values.alertmanager.smtp_smarthost }}'
      smtp_from: '{{ .Values.alertmanager.smtp_from }}'
      smtp_auth_username: '{{ (lookup "v1" "Secret" "monitoring" "alertmanager-smtp-secret").data.smtp_username | b64dec }}'
      smtp_auth_password: '{{ (lookup "v1" "Secret" "monitoring" "alertmanager-smtp-secret").data.smtp_password | b64dec }}'
      smtp_require_tls: true

    route:
      receiver: 'email'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m

    receivers:
    - name: 'email'
      email_configs:
      - to: '{{ .Values.alertmanager.smtp_to }}'
