apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasource-config
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ .Values.prometheus.release }}-kube-prometheus-sta-prometheus.{{ .Values.prometheus.namespace }}:9090
        access: proxy
        isDefault: true
        editable: true