apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-dashboard-vol
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
          env:
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: /var/lib/grafana/dashboards/app-custom-metrics.json
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
      volumes:
        - name: grafana-dashboard-vol
          configMap:
            name: grafana-dashboard-app
        - name: grafana-provisioning
          configMap:
            name: grafana-dashboard-provisioning
