apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  labels:
    app: grafana
    grafana_dashboard: "1"
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
