apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
      name: http
  type: ClusterIP
