apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-vs
spec:
  hosts:
  - "{{ .Values.ingress.host }}"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-app-frontend-service
        subset: v1
        port:
          number: {{ .Values.appFrontend.servicePort | default 80 }}
      weight: 60
    - destination:
        host: {{ .Release.Name }}-app-frontend-service
        subset: v2
        port:
          number: {{ .Values.appFrontend.servicePort | default 80 }}
      weight: 40
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-app-service-vs
spec:
  hosts:
  - "{{ .Values.ingress.host }}"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /app/
    route:
    - destination:
        host: {{ .Release.Name }}-app-service
        port:
          number: {{ .Values.appService.servicePort | default 80 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-model-service-vs
spec:
  hosts:
  - "{{ .Values.ingress.host }}"
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /model/
    route:
    - destination:
        host: {{ .Release.Name }}-model-service
        port:
          number: {{ .Values.modelService.servicePort | default 80 }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
    - "kiali.local"
  gateways:
    - default/{{ .Release.Name }}-gateway
  http:
  - match:
      - uri:
          prefix: /
    route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
    - "prometheus.local"
  gateways:
    - default/{{ .Release.Name }}-gateway
  http:
  - match:
      - uri:
          prefix: /
    route:
      - destination:
          host: prometheus.istio-system.svc.cluster.local
          port:
            number: 9090