apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-frontend-service
  labels:
    app: app-frontend-serv
spec:
  selector:
    app: app-frontend
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: {{ .Values.appFrontend.port }}
  type: ClusterIP