apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alerts@example.com'
    route:
      group_by: ['alertname']
      receiver: 'team-email'
    receivers:
    - name: 'team-email'
      email_configs:
      - to: 'ops@example.com'