apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-service
  labels:
    app: model-service
spec:
  selector:
    app: model-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP