apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: app-service
spec:
  selector:
    app: app-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.appService.port }}
  type: ClusterIP