---
- hosts: all
  become: yes
  tasks:
    - name: Set up multiple authorized keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ item }}"
      with_file:
        - public_keys/shreyas-provision-key.pub
