---
- hosts: node-*
  become: yes
  tasks:
    - name: Placeholder task
      debug:
        msg: "Provisioning for {{ inventory_hostname }} is not yet implemented."
    - name: Generate Kubernetes join command on controller
      command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      run_once: true

    - name: Join the node to the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

