apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | default (printf "%s.app.local" .Release.Name) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-frontend-service
                port:
                  number: {{ .Values.appFrontend.servicePort | default 80 }}
          - path: /app/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-service
                port:
                  number: {{ .Values.appService.servicePort | default 80 }}
          - path: /model/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-model-service
                port:
                  number: {{ .Values.modelService.servicePort | default 80 }}