apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-deployment
  labels:
    app: app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: ghcr.io/remla25-team15/app-frontend
          ports:
            - containerPort: 3000 # Replace with Helm: {{ .Values.appFrontend.port }}
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-frontend-config
                  key: flask_env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-frontend-config
                  key: name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-frontend-config
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: app-frontend-config
                  key: host
            - name: APP_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-frontend-config
                  key: app_service_url
