apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
  labels:
    app: app-frontend-serv
spec:
  selector:
    app: app-frontend
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000 # Replace with Helm: {{ .Values.appFrontend.port }}
  type: ClusterIP
