apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  namespace: default
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-frontend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics
    interval: 1s