apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  namespace: monitoring
  labels:
    release: myprom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: app-frontend-serv
  endpoints:
  - interval: 1s
    port: web
    path: /metrics