apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service-config
data:
  flask_env: "production" # Replace with Helm: {{ .Values.env.FLASK_ENV }}
  name: "model-service" # Replace with Helm: {{ .Values.modelService.host }}
  port: "5001" # Replace with Helm: {{ .Values.modelService.port }}
  host: "0.0.0.0" # Replace with Helm: {{ .Values.modelService.hostIP }}

