apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  labels:
    app: model-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: ghcr.io/remla25-team15/model-service
          ports:
            - containerPort: 5001 # Replace with Helm: {{ .Values.modelService.port }}
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: model-service-config
                  key: flask_env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: model-service-config
                  key: name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: model-service-config
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: model-service-config
                  key: host
            - name: MODEL_RESOURCE_URI
              valueFrom:
                secretKeyRef:
                  name: model-service-secrets
                  key: MODEL_RESOURCE_URI
            - name: CV_URI
              valueFrom:
                secretKeyRef:
                  name: model-service-secrets
                  key: CV_URI
          volumeMounts:
            - name: model-cache
              mountPath: /models

      volumes:
        - name: model-cache
          hostPath:
            path: /mnt/shared/models
            type: DirectoryOrCreate # Create it if it doesn't exist
