apiVersion: v1
kind: Secret
metadata:
  name: model-service-secrets
type: Opaque
data:
  MODEL_RESOURCE_URI: aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xRjZpLS1MNTBwVm03cDBkY0FwR0loZXBDN0NvdkMzTGEvdmlldz91c3A9c2hhcmluZw==
  # Replace with helm: { { .Values.modelService.secrets.MODEL_RESOURCE_URI | quote } }
  CV_URI: aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xNGJDWnUybU1VXzkwbmdaTERYeVFoOWZRQ2JxRFcwRS0vdmlldz91c3A9c2hhcmluZw==
  # Replace with heml: { { .Values.modelService.secrets.CV_URI | quote } }
